server:
  port: 8765

spring:
  application:
    name: api-gateway


  config:
    import: optional:configserver:http://localhost:8888

# sampling only a percentage of the request rather than every request 0.1 - 10%,
# though we want to sample all
  sleuth:
    sampler:
      probability: 1.0

#calling apis registered with eureka through api gateway  ALTERNATIVE: ROUTE in RouteLocator
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          # this ensures application names should be lower-cased
#          lower-case-service-id: true

#default
##spring.zipkin.base-url= http://localhost:9411/
##spring.zipkin.sender.type= rabbit   # rabbit, activemq, kafka, web


#connect to naming server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  # ensures all instances are registered when using random port
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

##multiple instances
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka,http://localhost:8762/eureka



#spring.cloud.gateway.discovery.locator.lower-case-service-id=true
