#must match properties file name in git repo
spring:
  application:
    name: limits-service

  config:
    import: optional:configserver:http://localhost:8888


  profiles:
    active: dev
#if profiles above is still picking default we can use spring.cloud.config.profile
  cloud:
    config:
#      profile: qa
      name: microservice-x-dev
       # if we want to fetch the config file using a different name other than the spring.application.name
       # we can use this property :spring.cloud.config.name

limits-service:
  minimum: 3
  maximum: 997
