apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-conversion
  strategy:
    rollingUpdate:
      maxSurge: 25% # how many instance should be created per time during release
      maxUnavailable: 25% # how many instances should be unavailable during release
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: currency-conversion
    spec:
      containers:
      - image: zikozee/base-currency-conversion-service:0.0.12-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: base-currency-conversion-service
        envFrom:
          - configMapRef:
              name: currency-conversion
#        config-map used below
#        env:
#          - name: CURRENCY_EXCHANGE_URI
#            value: http://currency-exchange
        readinessProbe: # ready to receive traffic
          httpGet:
            port: 8100
            path: /actuator/health/readiness
        livenessProbe: # restart if not up
          httpGet:
            port: 8100
            path: /actuator/health/liveness
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
spec:
  ports:
    - port: 8100
      protocol: TCP
      targetPort: 8100
  selector:
    app: currency-conversion
  sessionAffinity: None
  type: LoadBalancer

---

apiVersion: v1
data:
  CURRENCY_EXCHANGE_URI: http://currency-exchange
kind: ConfigMap
metadata:
  name: currency-conversion
  namespace: default