server:
  port: 8100
spring:
  application:
    name: currency-conversion

  config:
    import: optional:configserver:http://localhost:8888

# sampling only a percentage of the request rather than every request 0.1 - 10%,
# though we want to sample all
  sleuth:
    sampler:
      probability: 1.0

#default
##spring.zipkin.base-url= http://localhost:9411/

#connect to naming server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
##multiple instances
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka,http://localhost:8762/eureka


