server:
  port: 8761

spring:
  application:
    name: naming-server

  config:
    import: optional:configserver:http://localhost:8888
eureka:
  client:
    # we don't want this server to register with itself, rather register others. ctrl  + click for more details
    register-with-eureka: false
    fetch-registry: false

