server:
  port: 8888

spring:
  application:
    name: spring-cloud-config-server

  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/zikoz/Desktop/JAVA/MAVEN/2021_PROJECTS/MAY/Microservices/git-localconfig-repo